### ISSUE TITLE
Is this firmware or software development kit?

### ISSUE THREAD

**Issue by elamn1** [pine64/OpenPineBuds#16] opened 2023-01-09 13:07 UTC
Is this community effort to create open firmware or software development kit (SDK) for PineBuds Pro?

"Community maintained firmware for PineBuds Pro"

"PineBuds Open Source SDK

This is just the SDK from the wiki (so far), with dockerfile setup to make building easier, and my reverse engineered bestool integrated. The docker image will build bestool for you first, then drop you into the dev container for building and flashing the buds."

**Comment by elamn1** [comment] 2023-01-09 13:11
If this is firmware, what stage do you think it is at? When the open firmware is developed, I'm very interested ordering own PineBuds Pro :)

**Comment by Ralim** [comment] 2023-01-09 13:29
This is a slowly improving build based on the open SDK, this is not the closed source firmware shipped on the buds at the moment.

This is currently _a_ community firmware build that is moving towards being more and more usable.

If you do not need ANC it's already daily-drivable.

The readme needs updates but I've been busy🥲
The title of open SDK is because that's where it started off/came from.

**Comment by elamn1** [comment] 2023-01-09 13:42
> This is an improving build based on the open SDK, this is not the closed source firmware shipped on the buds at the moment.
> 
> This is currently _a_ community firmware build that is moving towards being more and more usable.
> 
> If you do not need ANC it's already daily-drivable.
> 
> The readme needs updates but I've been busysmiling_face_with_tear The title of open SDK is because that's where it started off/came from.

Currently and from now on this is only firmware.
It's currently enough stable to be daily driver, but some features are missing, such as ANC.
Right?

But it was the SDK, that eventually became the firmware? Was that SDK created from scratch or what was it based on? Could you also explain, how it was before SDK and now firmware? I can't understand how the [software development kit](https://en.wikipedia.org/wiki/Software_development_kit) becomes firmware😅... Usually SDK is made for software/operating system.

**Comment by WebWire-NL** [comment] 2023-01-09 18:13
Would be nice pine had released the SDK on github so everyone could fork the original SDK (Software Development Kit) and we could keep track of forks.
It's getting messy already.

https://imgur.com/a/QuYMkM9

**Comment by gamelaster** [comment] 2023-01-09 18:42
> Would be nice if pine64 had released the original SDK on github (or should we consider this as the original SDK now?)so everyone could fork the original SDK (Software Development Kit) and we could keep track of changes and forks.
It's getting messy already.

Note, PINE64 is a community, not a company. Pine Store, which provided this SDK from vendor, wants to keep the downloadable only as archive, from the wiki. Although, I think this should be consider this firmware, as community-improved SDK for any other development.

 > Your message about the original firmware suggests we can't reproduce the original software by using the original SDK? I'm kinda confused what we should consider as the original SDK. It would be logical for me that the original firmware would be reproducible by the original SDK (including needed proprietary blobs)

That's correct, the released SDK and this firmware can't reproduce firmware shipped with PineBuds Pro. It is due the fact, that ANC technology is under NDA, so vendor couldn't provide source code with this technology to the community.

> I'm probably asking this to the wrong people but there seems no central place where firmware's and SDK's are being discussed.

This is definitely the correct place for this. (maybe we could use Discussions feature for this, instead of creating issues).

**Comment by elamn1** [comment] 2023-01-09 19:20
> @elamn1 hello! This thing partially happened because of me, since we only recently moved this repo under pine64 org, and I made that "open firmware text".

Because of you? What "open firmware text"? Do you mean "Community maintained firmware for PineBuds Pro" text?

> This repository began as @Ralim 's effort of building the Software Development Kit (later SDK), which was provided by vendor to us.

You mean Ralimi's effort to improve the already existing open-source SDK? You said "which was provided by vendor to us.". And who is the "vendor"? Pine Store or someone else?

> In mean time, it received some improvements and nice stuff from Ralim and other contributors, so it changed into the open-source Pine Buds firmware, made by community. But it is still based on open-source SDK, provided by vendor.

So, you improved the SDK that you got from the "vendor" and it became firmware. I understood it. What I don't understand is how the SDK becomes firmware? The SDK reminds me of something like the Android SDK... So what kind of SDK was it and what did it do? Could you describe it a bit. Could it SDK flash to PineBuds Pro?

**Comment by elamn1** [comment] 2023-01-09 19:33
@WebWire-NL 
> Your message about the original firmware suggests we can't reproduce the original software by using the original SDK? I'm kinda confused what we should consider as the original SDK. It would be logical for me that the original firmware would be reproducible by the original SDK (including needed proprietary blobs)

"suggests we can't reproduce the original software by using the original SDK?" what do you mean?

**Comment by WebWire-NL** [comment] 2023-01-09 23:29
@elamn1 An SDK is just a Software Development Kit, another layer between the language you're programming used to create software (in this case firmware) for a specific Goal. The SDK can expose certain API's which are needed to make the software. The android SDK has all kind of tools and levels to develop android software. In the Android SDK case it's including an emulator and all API's needed to develop an android program, let's say you want to access the microphone the SDK provides you a way to access the microphone.

I think you can compare this SDK more with the AOSP source on android which provides the tools to build a whole Operating System (Android). There's also tools to cross compile against a different CPU architecture.

The original SDK is provided by pine64 as i read doesn't include certain components like the ANC component because it seems to contain proprietary components (non open-source), normally when these cases happen they provide these components as pre-compiled components so you can still create the firmware from scratch. But i think in this case it's due to licensing that this component is not released.

You can still download the original firmware but not the source which is used by pine64 to create the firmware.
https://wiki.pine64.org/wiki/PineBuds_Pro#Software_releases

**Closed** 2023-01-22 10:05 UTC
